### ISSUE TITLE
Generated Swagger file has invalid path parameters (RFC 8040)

### ISSUE THREAD

**Issue by mkieweg** [mbj4668/yanger#22]
When generating a swagger file with path parameters the parameter is escaped like this:
```json
"/path/with/key={value}":{}
```

where it should be
```
"/path/with/{key=value}":{}
```

to be RFC8040 compliant. This also makes more sense semantically since a RESTCONF path parameter consists of leaf-list name (`key`) and leaf-list value as defined in [3.5.3](https://tools.ietf.org/html/rfc8040#page-26) of RFC8040

This causes for example the go-openapi route builder to parse the route incorrectly. The route builder expects a valid RESTful and/or RESTCONF compliant path.

**Comment by mbj4668** [comment]
Unfortunately I don't know anything about swagger, and the author of the swagger plugin is not active in this project anymore.

**Comment by ksallberg** [comment]
@boisjacques Will you provide a PR for this? Or at least provide a reproduceable test case with YANG that causes this to happen?

**Comment by mkieweg** [comment]
Since I have no experience with Erlang looking into the code of the plugin wasn't too successful, so unfortunately no PR. But this minimal YANG file causes the issue. 
```yang
module debug {
    yang-version 1.1;
    namespace "urn:example:params:xml:ns:yang:example";
    prefix if;

    organization
    "example";

    description
    "example";

    revision "2020-08-17" {
    description
        "Initial Revision";
    }

    container interfaces {
        list interface {
            config false;
            key "name";
            leaf name {
                type string;
                mandatory "true";
                description
                "Interface name. Example value: en0";
            }
        }
    }
}
```

The invalid path can be found in line 648 in the output. The output was generated using a Docker container built today from master (1c6a234)

**Comment by ksallberg** [comment]
I suppose I could take this on for fun, but I have no idea what the resulting JSON ought to look like, you would need to help me out there. After a very quick and dirty hacking session, the line you pointed out looks like this:

`"/data/debug:interfaces/{interface=interface-name}": {`

I have no clue if this is better or worse. Why is 'interface' present on both sides of the equal sign? Is that right or wrong?

Also, should this behaviour be changed for lists only, or leaf-lists too?

**Comment by mkieweg** [comment]
Thank you!

The resulting JSON should look the way you mentioned. The snytax is a bit confusing with that part. Imagine a normal RESTful path parameter like `/foo/{parameter}/bar` where `{parameter}` can be `/foo/1/bar` or `/foo/2/bar`. In RESTCONF a path parameter contains a key and a value consisting of the list name and the list's key. Hence the equal sign and two times interface. The key is in that case `interface`and the value is `interface-name`.

This behaviour should be consistent with all path parameters.

**Comment by avtobiff** [comment]
I will have to review the path yanger produces for swagger, but the key is implicit.

I.e. `/data/debug:interfaces/interface={name}` would be correct, there is no explicit mention of the key
in the path. The path would be `/data/debug:interfaces/interface=eth0` for instance.

**Comment by avtobiff** [comment]
Another option would be to have `/path/list={key-value}`, as stated above.

**Comment by mkieweg** [comment]
> I.e. `/data/debug:interfaces/interface={name}` would be correct

You are right. This issue is not a yanger issue at all. Found the problem a couple steps further down while looking at the HTTP router. Yanger works correct in this regard and the issue can be closed.
