### ISSUE TITLE
--depend-recurse option for depend plugin

### ISSUE THREAD

**Issue by pmerlo74** [mbj4668/yanger#30]
Today we're using the "--depend-recurse" option for the depend plugin with pyang for a use-case that we are investigating to move to yanger.

Just curious if there is any technical reason not to support this with yanger - if none then I have a proposed fix to address this option for which I can open a PR.

**Comment by mbj4668** [comment]
No technical reasons!  A PR is welcome!

**Comment by pmerlo74** [comment]
Fixed in https://github.com/mbj4668/yanger/pull/32
