### ISSUE TITLE
Can yanger be used to do XML instance validation

### ISSUE THREAD

**Issue by nsridevius** [mbj4668/yanger#6]
Can yanger be used to Instance Validation ? I was referring to other link https://github.com/mbj4668/pyang/wiki/InstanceValidation.
the pyang was great in generating relaxng/schematron schemas, however it stumbled when yang modules used yang 1.1 statements like deref or when using any xpath statements that are not standard xpath 1.0/2.0 that ISO schematron does not understand

If yanger can do instance validation? can somebody provide examples 

thanks
Sri

**Comment by mbj4668** [comment]
No, yanger cannot currently do instance validation.  Check out libyang: https://github.com/CESNET/libyang
