### ISSUE TITLE
Is there documentation anywhere?

### ISSUE THREAD

**Issue by Hubro** [mbj4668/yanger#9]
Is the yanger tool with all its options documented anywhere?

For example, I have no idea what the various options for the `--transform` flag does.

Specifically though, I'm trying to export a Swagger spec for a NSO service model. This model includes `uses ncs:service-data`, which adds a *lot* of noise, none of which I need for my API documentation. Are there any options for yanger that can help with filtering all that away, or must it be done manually?

**Comment by mbj4668** [comment]
No, currently there is no real documentation :( 
yanger -h may give some hints.

As for filtering out stuff in swagger, perhaps you can use --swagger-path-filter?

**Comment by Hubro** [comment]
The help text helps a little, but it's very terse so it doesn't help a lot :sweat_smile: 

I'm already using `--swagger-path-filter` to select the model I want to export, but unfortunately the `using ncs:service-data` statement riddles the model with actions and operational data, bloating the Swagger spec. After running the resulting spec through `jq` to format it, it's almost 60 000 lines. My browser freezes indefinitely when I try to load the spec into Swagger Editor :sweat_smile: 

I'm working on a script to filter all that out though.
